import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBox from '../components/SearchBox'
import DeckGLMap from '../components/DeckGLMap'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Radar Events Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
       Radar`&apos;`s Places
      </h1>

      <SearchBox />
      <DeckGLMap />

    </>
  )
}

export default Home
